### PR TITLE
Proper call of calloc()

### LINKED ISSUE #868: Wrong usage of calloc()
A quick look gives:
```
$ git grep calloc
c_speech_features/c_speech_features.c:    energy = (csf_float*)calloc(sizeof(csf_float), n_frames);
c_speech_features/c_speech_features.c:  feat = (csf_float*)calloc(sizeof(csf_float), n_frames * aNFilters);
c_speech_features/c_speech_features.c:  feat = (csf_float*)calloc(sizeof(csf_float), n_frames * aNFilters);
c_speech_features/c_speech_features.c:  ssc = (csf_float*)calloc(sizeof(csf_float*), n_frames * aNFilters);
c_speech_features/c_speech_features.c:  delta = (csf_float*)calloc(sizeof(csf_float), aNFrames * aNFrameLen);
c_speech_features/c_speech_features.c:    (csf_float*)calloc(sizeof(csf_float), aNFilters * feat_width);
c_speech_features/c_speech_features.c:  win_correct = (csf_float*)calloc(sizeof(csf_float), aSigLen);
c_speech_features/c_speech_features.c:  signal = (csf_float*)calloc(sizeof(csf_float), aSigLen);
```

While manpage states:
```
       void *calloc(size_t nmemb, size_t size);
[...]
       The calloc() function allocates memory for an array of nmemb elements of size bytes each and returns a pointer to the allocated memory.  The memory is set to zero.  If nmemb or size is 0, then calloc() returns either NULL, or a unique pointer
       value that can later be successfully passed to free().
```

So the first argument is the number of elements, and the second argument is the size of each one of them. Our calls are inverting both.

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #868

### CODE REVIEW

File: native_client/c_speech_features/c_speech_features.c [hunk 1]
```diff
@@ -217,7 +217,7 @@ csf_ssc(const short* aSignal, unsigned int aSignalLen, int aSampleRate,
   }
 
   // Calculate Spectral Sub-band Centroid features
-  ssc = (csf_float*)calloc(sizeof(csf_float*), n_frames * aNFilters);
+  ssc = (csf_float*)calloc(n_frames * aNFilters, sizeof(csf_float*));
```
Comment (reuben) [inline native_client/c_speech_features/c_speech_features.c]: Looks like there's another bug here, it should be allocating elements of size  `sizeof(csf_float)` not `sizeof(csf_float*)`.

Comment (lissyx) [reply native_client/c_speech_features/c_speech_features.c]: Good catch, I went quickly this morning and just fixed the arguments order.
