### PR TITLE
Ensure proper removal of prefix

### LINKED ISSUE #2230: `Invalid read size` reported by valgrind
```
  ==28087== 2230 errors in context 2 of 26:                                       
  ==28087== Invalid read of size 4                                                
  ==28087==    at 0x8DCFD62: decoder_decode(DecoderState*, Alphabet const&, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:167)
  ==28087==    by 0x8DCD521: ModelState::decode_raw(DecoderState*) (modelstate.cc:47)
  ==28087==    by 0x8DCD7E6: ModelState::decode_metadata(DecoderState*) (modelstate.cc:61)
  ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
  ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0x17A1FE8842FC: ???                                             
  ==28087==    by 0x17A1FE93D195: ???                                             
  ==28087==    by 0x17A1FE88535E: ???                                             
  ==28087==    by 0x17A1FE93D195: ???                                             
  ==28087==  Address 0x7ed1114 is 20 bytes inside a block of size 112 free'd      
  ==28087==    at 0x4839E7B: operator delete(void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
  ==28087==    by 0x8DCF040: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:151)
  ==28087==    by 0x8DCBA3F: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (deepspeech.cc:255)
  ==28087==    by 0x8DCC490: StreamingState::finishStreamWithMetadata() (deepspeech.cc:149)
  ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
  ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0x17A1FE8842FC: ???                                             
  ==28087==    by 0x17A1FE93D195: ???                                             
  ==28087==    by 0x17A1FE88535E: ???                                             
  ==28087==  Block was alloc'd at                                                 
  ==28087==    at 0x4838DBF: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
  ==28087==    by 0x8DE2AB1: PathTrie::get_path_trie(int, int, float, bool) (path_trie.cpp:72)
  ==28087==    by 0x8DCEBB1: decoder_next(double const*, Alphabet const&, DecoderState*, int, int, double, unsigned long, unsigned long, Scorer*) (ctc_beam_search_decoder.cpp:103)
  ==28087==    by 0x8DCBA3F: StreamingState::processBatch(std::vector<float, std::allocator<float> > const&, unsigned int) (deepspeech.cc:255)
  ==28087==    by 0x8DCC490: StreamingState::finishStreamWithMetadata() (deepspeech.cc:149)
  ==28087==    by 0x8DCC4BE: DS_FinishStreamWithMetadata (deepspeech.cc:390)      
  ==28087==    by 0x4854495: _wrap_SpeechToTextWithMetadata(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/alex/tmp/deepspeech/0.6.0a1/node_modules/deepspeech/lib/binding/v0.6.0-alpha.1/linux-x64/node-v59/deepspeech.node)
  ==28087==    by 0xAA0F12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB17F3B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::Bu  iltinArguments) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0xB18B8E: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/alex/tmp/deepspeech/0.6.0a1/node-v9.11.2-linux-x64/bin/node)
  ==28087==    by 0x17A1FE8842FC: ???                                             
  ==28087==    by 0x17A1FE93D195: ???
```

Locally reverting https://github.com/mozilla/DeepSpeech/commit/95a54bfdb8b2f9d0d2b85cc7b8438c4b11be7e57 fixes the issue, so it's a regression from #2184

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #2230

### CODE REVIEW

**Comment by lissyx** [comment]
Properly removing the element from the `std::vector` data structure does get rid of the valgrind-level error for me.

File: native_client/ctcdecode/ctc_beam_search_decoder.cpp [hunk 1]
```diff
@@ -149,6 +149,8 @@ decoder_next(const double *probs,
                        prefix_compare);
       for (size_t i = beam_size; i < state->prefixes.size(); ++i) {
         state->prefixes[i]->remove();
+        // Remove the element from std::vector
+        state->prefixes.erase(state->prefixes.begin() + i);
```
Comment (reuben) [inline native_client/ctcdecode/ctc_beam_search_decoder.cpp]: This loop is erasing everything from beam_size to the end of the vector, so this can be a single erase call outside of the loop:

```C++
state->prefixes.erase(state->prefixes.begin() + beam_size, state->prefixes.end());
```

Comment (reuben) [reply native_client/ctcdecode/ctc_beam_search_decoder.cpp]: Or alternatively:

```
state->prefixes.resize(beam_size);
```

Comment (lissyx) [reply native_client/ctcdecode/ctc_beam_search_decoder.cpp]: That's not completely wrong, I wrote it in a hurry ☺️
