### PR TITLE
Only update time step of leaf prefixes (Fixes #2294)

### LINKED ISSUE #2294: Wrong character timings from ctc_decoder
- I have written a few lines to output character timings in native_client/python/client.py: (l. 59)

```python
def metadata_to_string(metadata):
    transcript = ''
    starts= ''
    for item in metadata.items:
        start= "{0:.3f}".format(item.start_time)
        starts += start
        transcript += start + "\t" + item.character + "\n"
    return transcript
```
- Linux Ubuntu 16.04 in Docker Image from Dockerfile 
- Exact command to reproduce: using your pretrained model 0.5.0, your lm, your smoke test audio (all from version 0.5.0) 

```bash
python native_client/python/client.py \ 
                --model deepspeech-0.5.0/model/output_graph.pb  \
                --alphabet deepspeech-0.5.0/model/alphabet.txt  \
                --lm deepspeech-0.5.0/model/lm.binary  \
                --trie deepspeech-0.5.0/model/trie  --extended \
                --audio data/smoke_test/LDC93S1_pcms16le_1_8000.wav \
 ```
- output is: 

0.340	s
0.520	h     *****
0.380	e  
0.480	 
0.520	h     *****
0.560	a
0.600	d
0.700	 
0.720	t
0.760	o
0.880	 
0.920	d
0.960	u
1.020	c
1.040	k
1.380	       *******
1.240	s
1.280	u
1.300	i
1.340	t
1.380	       *******
1.420	a
1.440	n
1.460	d
1.500	 
1.540	g
1.580	r
1.620	e
1.660	a
1.680	s
1.800	y
1.880	 
1.960	w
2.000	a
2.040	s
2.280	t
2.360	e
2.440	 
2.500	a
2.660	 
2.740	y
2.760	e
2.780	a
2.820	r

- there is a bug  (*****) in the start_timings in some cases and I'm not sure, but I think it's happing somwhere in these lines in path_trie.cpp. I don't really know what is saved in children, but I guess too much as it's using the same late "h" time in "she" as in "had", so the "h" in had has apparently a higher probabilty ?! It's in native_client/ctcdecode/path_trie.cpp l.38-48

```cpp
PathTrie* PathTrie::get_path_trie(int new_char, int new_timestep, float cur_log_prob_c, bool reset) {
  auto child = children_.begin();
  for (child = children_.begin(); child != children_.end(); ++child) {
    if (child->first == new_char) {
      if (child->second->log_prob_c < cur_log_prob_c) {    // here is the problem?
        child->second->log_prob_c = cur_log_prob_c;
        child->second->timestep = new_timestep;
      }
      break;
    }
  }
```

### PR DESCRIPTION
**Pull request by reuben**
The intention of this check is to improve the accuracy of the timings by recording the time step where the character saw its highest probability rather than the first time step where it was seen. The problem happens when updating the time step of a prefix that already has children. In that case, if any of the children have a time step that is earlier than `new_timestep`, it'll break the linearity of the timings. My fix is to simply check that the prefix we're updating is a leaf.

For example, say during decoding we have the following beams (format is `(char | time)`, tree node id below, nodes with same id are the same object):

```
1. (-1 | 0 ) -> ('s' | 10) -> ('h' | 13) -> ('e' | 14)
       A             B             C             D

2. (-1 | 0 ) -> ('s' | 10) -> ('h' | 14)
       A             B             E
```

And the prefix list is `[B, C, D, E]`. Currently, if we process character 'h' in time step 15 with a probability higher than both C and E, we update both nodes to have time step 15, which breaks linearity in beam 1. With my fix, we only update node E, which is a leaf. In my tests this does fix the problem, but since we don't have any known good quality data to verify against, it's hard to know if it has other side effects.

### CODE REVIEW

**Comment by reuben** [comment]
@dabinat, since you did the work to expose timings in the API, maybe you have some tooling for checking/visualizing the impact of this change, or at least better intuition on timing quality?

**Comment by dabinat** [comment]
@reuben Letter timings are generally late and it sounds like this may make them earlier, which should improve accuracy. I wrote a script to take the output from DeepSpeech 0.5.1 and split it into clips of up to 8 words (approximating a sentence) and found through trial and error that subtracting 0.1 seconds from the start point prevented it from getting cut off in almost all circumstances.

A big problem I have is testing features that require accurate models because master is often incompatible with the most recent release model and it’s infeasible for me to train a model from scratch every time a breaking change occurs. So I’m experimenting a lot with 0.5.1 but my ability to test certain features on 0.6 is limited.

**Comment by reuben** [comment]
@dabinat thanks! sorry for the inconvenience with the breaking changes. FWIW, there's a 0.5.1 model re-exported for current master available here, which we use for tests: https://github.com/reuben/DeepSpeech/releases/v0.6.0-alpha.4

**Comment by rhamnett** [comment]
@reuben is there any chance we can get a checkpoint directory for 0.6 with all the corpus training? I can't do any further experiments right now.

File: native_client/ctcdecode/path_trie.cpp [hunk 1]
```diff
@@ -39,7 +39,8 @@ PathTrie* PathTrie::get_path_trie(int new_char, int new_timestep, float cur_log_
   auto child = children_.begin();
   for (child = children_.begin(); child != children_.end(); ++child) {
     if (child->first == new_char) {
-      if (child->second->log_prob_c < cur_log_prob_c) {
+      if (child->second->log_prob_c < cur_log_prob_c &&
+          child->second->children_.size() == 0) {
```
Comment (lissyx) [inline native_client/ctcdecode/path_trie.cpp]: Maybe worth commenting that if we update elements that are not leafs, we will overwrite earlier timecodes.
