### PR TITLE
Fix possible NULL deref on result->string

### LINKED ISSUE #457: Fix possible NULL deref in client.cc

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #457

### CODE REVIEW

**Comment by lissyx** [comment]
Also moved free(result); within the if (result) for consistency

File: native_client/client.cc [hunk 1]
```diff
@@ -135,16 +135,20 @@ main(int argc, char **argv)
   // Pass audio to DeepSpeech
   struct ds_result* result = LocalDsSTT(ctx, (const short*)buffer, buffer_size / 2, sampleRate);
   if (result) {
-    printf("%s\n", result->string);
+    if (result->string) {
+      printf("%s\n", result->string);
+      free(result->string);
+    }
+
     if ((argc == 4) && (strncmp(argv[3], "-t", 3) == 0)) {
```
Comment (Cwiiis) [inline native_client/client.cc]: Heh, just also noticed that this ought to be >=4 (or the check at the top of the file needs to be changed) :)
