### PR TITLE
Move init of previous_state_{c,h}

### LINKED ISSUE #2125: Android Native client results inconsistent across multiple runs
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android P
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Your builds
- **TensorFlow version (use command below)**: Not applicable 
- **Python version**: Not applicable
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: Not Applicable
- **GPU model and memory**: Not Applicable
- **Exact command to reproduce**: 

Trying to run DeepSpeech 0.4.1 native_client on Android P platform with tflite model of DeepSpeech 0.4.1 ckpts.

When the client is run multiple times on same set of wav files the results are inconsistent.

In detail,
we have a folder with set of, say, 4 wav files, each copy of same one wav file.

Now if we run
`./deepspeech --model /docker_files/checkpoints_0_4_1_mozilla/output_graph_original.tflite --alphabet /docker_files/lm_own_v3/alphabet.txt --audio /docker_files/wavs/wav1/`

we get 

```
> > /data/local/wav1//call_9890278956_MAIN.wav
>  gol nin ight nines yelooked to seven eight nine five six
> > /data/local/wav1//call_9890278956_COPY1.wav
>  gol nine eight nine elook two seven eight nine five six
> > /data/local/wav1//call_9890278956_COPY2.wav
>  gol nine eight nine elo two seven eight nine five six
> > /data/local/wav1//call_9890278956_COPY3.wav
>  gol nine eight nine zelo two seven eight nine five six
```
Note that we are giving the path of folder that contains all the four wav files. The results are inconsistent even if we run with LM and trie and with different set of wav files.

While if we take each wav file individually and run the same above command, the output is consistent. It's always
`gol nine ight names yelooked to seven eight nine fivt six`

NOTE: We didn't find this inconsistency issue when working on Linux native client using .pb files and the same above wav files

### PR DESCRIPTION
**Pull request by lissyx**
Fixes #2125

### CODE REVIEW

File: native_client/deepspeech.cc [hunk 1]
```diff
@@ -843,6 +831,18 @@ DS_SetupStream(ModelState* aCtx,
 
   ctx->model = aCtx;
 
+  TfLiteIntArray* dims_c = ctx->model->interpreter->tensor(ctx->model->previous_state_c_idx)->dims;
+  TfLiteIntArray* dims_h = ctx->model->interpreter->tensor(ctx->model->previous_state_h_idx)->dims;
+  assert(dims_c->data[1] == dims_h->data[1]);
+
+  ctx->model->previous_state_size = dims_c->data[1];
+  ctx->model->previous_state_c_.reset(new float[ctx->model->previous_state_size]());
```
Comment (reuben) [inline native_client/deepspeech.cc]: We don't need to re-allocate on every new stream, just re-initialize.

Comment (reuben) [reply native_client/deepspeech.cc]: And the state size as well will not change between streams.
