### PR TITLE
Don't save/load trie for character based LMs (Fixes #1756)

### LINKED ISSUE #1756: segmentation fault on generate_trie
Hey guys,

I'm following this tutorial to use DeepSpeech on my own data (Japanese): https://discourse.mozilla.org/t/tutorial-how-i-trained-a-specific-french-model-to-control-my-robot/22830

I created the training/valid/test csv files correctly, and I got the alphabet, vocab and lm.binary. When I was trying to create the trie I got segmentation fault...

I followed this https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md to get the pre-built binaries with util/taskcluster.py, and use ./generate_trie alphabet.txt lm.binary trie. Did i miss something?

thanks

### PR DESCRIPTION
**Pull request by reuben**
Something like this. Should be backwards compatible.

### CODE REVIEW

File: native_client/ctcdecode/scorer.cpp [hunk 1]
```diff
@@ -134,8 +136,10 @@ void Scorer::save_dictionary(const std::string& path)
   fout.write(reinterpret_cast<const char*>(&MAGIC), sizeof(MAGIC));
   fout.write(reinterpret_cast<const char*>(&FILE_VERSION), sizeof(FILE_VERSION));
   fout.write(reinterpret_cast<const char*>(&is_character_based_), sizeof(is_character_based_));
-  fst::FstWriteOptions opt;
-  dictionary->Write(fout, opt);
+  if (!is_character_based_) {
```
Comment (lissyx) [inline native_client/ctcdecode/scorer.cpp]: So technically we will still produce a trie file :)

Comment (reuben) [reply native_client/ctcdecode/scorer.cpp]: Yep. My reasoning is that it simplifies the documentation, everyone follows the same steps, even if for character based LMs the trie file will be a tiny dummy file. Also simplifies the code changes.

Comment (lissyx) [reply native_client/ctcdecode/scorer.cpp]: 100% agree with you
